# /etc/rspamd/local.d/fuzzy_check.conf

# https://docs.rspamd.com/modules/fuzzy_check

# merge this into an existing file

rule "rqwatch" {
  algorithm = "mumhash";
  servers = "localhost:11335";
  symbol = "RQWATCH_FUZZY_UNKNOWN";
  mime_types = ["*"];
  # old versions of rspamd might need: max_score = 20.0;
  # https://docs.rspamd.com/modules/fuzzy_check/#max_score--hits_limit-parameter
  hits_limit = 20.0;
  read_only = false;
  skip_unknown = true;
  short_text_direct_hash = true;
  min_length = 64;
  fuzzy_map = {
    RQWATCH_FUZZY_DENIED {
      # see above for max_score / hits_limit parameter
      hits_limit = 20.0;
      flag = 11;
    }
    RQWATCH_FUZZY_WHITE {
      hits_limit = 20.0;
      flag = 13;
    }
  }
}
