# /etc/rspamd/local.d/fuzzy_check.conf

# https://docs.rspamd.com/modules/fuzzy_check

# merge this into an existing file

rule "rqwatch" {
  algorithm = "mumhash";
  servers = "localhost:11335";
  symbol = "RQWATCH_FUZZY_UNKNOWN";
  mime_types = ["*"];
  hits_limit = 20.0;
  read_only = false;
  skip_unknown = true;
  short_text_direct_hash = true;
  min_length = 64;
  fuzzy_map = {
    RQWATCH_FUZZY_DENIED {
      hits_limit = 20.0;
      flag = 11;
    }
  }
}
