# /etc/rspamd/local.d/fuzzy_group.conf

# merge this into an existing file

symbols = {
  "RQWATCH_FUZZY_DENIED" {
    weight = 5.0;
    description = "Local fuzzy hash, learned as spam in rqwatch";
  }
  "RQWATCH_FUZZY_WHITE" {
    weight = -5.0;
    description = "Local fuzzy hash, learned as not spam in rqwatch";
  }
  "RQWATCH_FUZZY_UNKNOWN" {
    weight = 0.0;
    description = "Local fuzzy hash, unknown flag";
  }
}
